---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureCluster
metadata:
  name: {{ CLUSTER_NAME }}
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: AzureClusterIdentity
    name: {{ CLUSTER_IDENTITY_NAME }}
  location: {{ AZURE_LOCATION }}
  networkSpec:
    subnets:
    - name: control-plane-subnet
      role: control-plane
    - name: node-subnet
      natGateway:
        name: node-natgateway
      role: node
    vnet:
      name: {{ AZURE_VNET_NAME or (CLUSTER_NAME ~ "-vnet") }}
  resourceGroup: {{ AZURE_RESOURCE_GROUP or CLUSTER_NAME }}
  subscriptionID: {{ AZURE_SUBSCRIPTION_ID }}
